#!/usr/bin/env python

from __future__ import print_function, unicode_literals

import sys, os
import subprocess

fin = open(sys.argv[1], "w")

proc = subprocess.Popen('/dev/shm/test', shell=True,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)

path = proc.communicate()

print("pwd: " + str(path), file=fin)
print("argv: " + str(sys.argv), file=fin)

fin.close()

sys.exit(0)

